# JavaScript 尝试…捕捉

> 原文:[https://www.javatpoint.com/javascript-try-catch](https://www.javatpoint.com/javascript-try-catch)

try…catch 是各种编程语言中常用的语句。基本上，它用于处理代码中容易出错的部分。它首先测试代码中可能包含的所有可能的错误，然后执行操作来处理这些错误(如果发生的话)。一个好的编程方法是将复杂的代码保存在 try…catch 语句中。

让我们分别讨论每个语句块:

**try{}语句:**这里，需要进行可能的错误测试的代码保存在 try 块中。如果出现任何错误，它将传递给 catch{}块，以便采取适当的操作并处理错误。否则，它将执行内部编写的代码。

**catch{}语句:**这个块通过执行写在块内的一组语句来处理代码的错误。该块包含用户定义的异常处理程序或内置处理程序。只有当任何容易出错的代码需要在 try 块中处理时，该块才会执行。否则，将跳过 catch 块。

#### 注意:catch {}语句仅在执行 try {}语句后执行。此外，一个 try 块可以包含一个或多个 catch 块。

### 语法:

```
try{
expression; } //code to be written.
catch(error){
expression; } // code for handling the error.

```

### 尝试…抓住例子

```
<html>
<head> Exception Handling</br></head>
<body>
<script>
try{
var a= ["34","32","5","31","24","44","67"]; //a is an array
document.write(a);    // displays elements of a
document.write(b); //b is undefined but still trying to fetch its value. Thus catch block will be invoked
}catch(e){
alert("There is error which shows "+e.message); //Handling error
}
</script>
</body>
</html>

```

[Test it Now](https://www.javatpoint.com/oprweb/test.jsp?filename=Javascripttry-catch)

## 抛出语句

Throw 语句用于引发用户定义的错误。用户可以定义并抛出自己的自定义错误。当执行 throw 语句时，它后面的语句将不会执行。控制将直接传递给 catch 块。

### 语法:

```
throw exception;

```

### 尝试…捕捉…抛出语法

```
try{
throw exception; // user can define their own exception
}
catch(error){
expression; }  // code for handling exception.

```

异常可以是字符串、数字、对象或布尔值。

### 试着举个例子…接住

```
<html>
<head>Exception Handling</head>
<body>
<script>
try {
   throw new Error('This is the throw keyword'); //user-defined throw statement.
}
catch (e) {
  document.write(e.message); // This will generate an error message
}
</script>
</body>
</html>

```

[Test it Now](https://www.javatpoint.com/oprweb/test.jsp?filename=Javascripttry-catch2)

借助 throw 语句，用户可以创建自己的错误。

## 尝试…捕捉…最后陈述

最后是一个可选的语句块，它在 try 和 catch 语句执行之后执行。Finally 块不支持抛出异常。不管是否抛出任何异常，最后块代码，如果存在，肯定会执行。它也不关心输出。

### 语法:

```
try{
expression;
}
catch(error){
expression;
}
finally{
expression; } //Executable code

```

### 尝试…抓住…最后一个例子

```
<html>
<head>Exception Handling</head>
<body>
<script>
try{
var a=2;
if(a==2)
document.write("ok");
}
catch(Error){
document.write("Error found"+e.message);
}
finally{
document.write("Value of a is 2 ");
}
</script>
</body>
</html> 

```

[Test it Now](https://www.javatpoint.com/oprweb/test.jsp?filename=Javascripttry-catch3)

因此，我们也可以一起使用 try/catch/throw/finally 关键字来处理复杂的代码。

* * *